// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlnukjjpqwiulfenshah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsbnVrampwcXdpdWxmZW5zaGFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTIyMTgsImV4cCI6MjA3MzI2ODIxOH0._Gm5OxJ1Nln0pidATRgecbq2qcqKKzxVW43X3zsZJPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});